vim.keymap.set("n", "<leader>n", ":Yazi<CR>", { desc = "Open Yazi for current dir" })
vim.keymap.set("n", "<leader>vc", function()
  vim.cmd("cd ~/.config/nvim")
  require("notify")("Changed Directory To ~/.config/nvim")
end, { desc = "Open Nvim config directory with default explorer" })
